baseURL = "https://plantindustrial.xyz"
languageCode = "en-US"
title = "Plant Industrial"
description = "a newsletter about the plant based economy."
config = "config.toml"
theme = "onepress"
# Enter your tracking code to enable Google Analytics
googleAnalytics = " "
# Disable comments by leaving disqusShortname empty
disqusShortname = ""
copyright = "Copyright © 2019, Sanju Ashok"
canonifyURLS = true
paginate = 12

[params]
	author = "Sanju Ashok"
	logo = "images/logo.png"
	enableRSS = true
	customCSS = true
        readMore = "Read More"

    subscribeLink = "https://tinyletter.com/plantindustrial"
    # Social
	twitter  = "https://twitter.com/sanjuashok"

    # Widget
    widgets = false

    # Author box and Share button
    authorCard = false
    shareButton = false

    # Code highlighting with highlight.js
    highlightJS = true

# Taxonomies
[taxonomies]
    tag = "tags"
